[package]
name = "wgpui-kit-macros"
description = "Macros for wgpui-component."
version = "0.6.1"
license = "Apache-2.0"
documentation = "https://docs.rs/wgpui-kit-macros"
homepage = "https://github.com/Muktidaya/wgpui"
repository = "https://github.com/Muktidaya/wgpui"
readme = "README.md"
publish = true
edition.workspace = true

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
proc-macro2 = "1.0"
proc-macro-crate = "3.5"
quote = "1.0"
syn = "2.0"

[package.metadata.cargo-machete]
ignored = ["proc-macro2", "core-text"]
